### ISSUE TITLE
grunt serve failing

### ISSUE THREAD

**Issue by shamb0t** [haadcode/orbit#226]
I'm having webpack issues...after a clean npm install, running npm run dev in client/ fails

<img width="1151" alt="screen shot 2017-02-01 at 1 28 50 pm" src="https://cloud.githubusercontent.com/assets/2730657/22501485/6ebbf80c-e882-11e6-97f4-fc0e6fa87dc2.png">

**Comment by haadcode** [comment]
Hi @shamb0t and thanks for reporting this. This issue comes from how the dev tools are setup for live reloading, webpack2 and webpack-dev-server. Webpack2 has been in beta for a long time (which Orbit uses) and they've finally upgraded to stable 2.x. Unfortuantely I haven't had the time to update the build tools yet, which means atm the live reloading is broken :/

Yu can, however, compile the app with `npm run build:app` (and minified `npm run build`) and then `npm start`. However, this means you'll have to run the build command everytime you change the code :/ It's a clumsy way of doing it but should work. I'll try to get to updating the build tools some time next week, but if you feel adventurous, feel free to try to make sense of it and update to webpack@2.2.0 and webpack-dev-server@2.2.1 (note that setting it up is not straight-forward, it may not be worth your effort).

**Comment by shamb0t** [comment]
Thanks @haadcode I'll try updating to webpack2 and if it takes too long I'll go the clumsy way I guess

**Comment by shamb0t** [comment]
It works with webpack 2 if I also update grunt-webpack and chunk-manifest-webpack-plugin which doesn't seem to break anything....any reason not to update those? If not I can push the changes

**Comment by haadcode** [comment]
Oh nice! No reason to *not* update them if that makes it work. Just make sure to push them to a branch :)

**Comment by haadcode** [comment]
Merged your fix to master @shamb0t.
